/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Ali
 */
public class KalkulatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form KalkulatorGUI
     */
    public KalkulatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        angka1Label = new javax.swing.JLabel();
        angkaLabel2 = new javax.swing.JLabel();
        aksiLabel = new javax.swing.JLabel();
        hasilLabel = new javax.swing.JLabel();
        angka1Text = new javax.swing.JTextField();
        angka2Text = new javax.swing.JTextField();
        aksiBox = new javax.swing.JComboBox<>();
        hasilText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Title.setText("Kalkulator Sederhana");

        angka1Label.setText("Angka 1:");

        angkaLabel2.setText("Angka 2:");

        aksiLabel.setText("Aksi:");

        hasilLabel.setText("Hasil:");

        aksiBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tambah", "Kurang", "Bagi", "Kali" }));
        aksiBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aksiBoxActionPerformed(evt);
            }
        });

        hasilText.setEditable(false);
        hasilText.setForeground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Title)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(angkaLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(angka1Label)
                            .addComponent(aksiLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hasilLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(angka1Text)
                            .addComponent(angka2Text)
                            .addComponent(hasilText)
                            .addComponent(aksiBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angka1Label)
                    .addComponent(angka1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angkaLabel2)
                    .addComponent(angka2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aksiLabel)
                    .addComponent(aksiBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasilLabel)
                    .addComponent(hasilText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aksiBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aksiBoxActionPerformed
        angka1 = Double.parseDouble(String.valueOf(angka1Text.getText()));
        angka2 = Double.parseDouble(String.valueOf(angka2Text.getText()));

        if (aksiBox.getSelectedItem() == "Tambah") {
            hasil = angka1 + angka2;
        }
        if (aksiBox.getSelectedItem() == "Kurang") {
            hasil = angka1 - angka2;
        }
        if (aksiBox.getSelectedItem() == "Bagi") {
            hasil = angka1 / angka2;
        }
        if (aksiBox.getSelectedItem() == "Kali") {
            hasil = angka1 * angka2;
        }

        tampil = Double.toString(hasil);
        hasilText.setText(tampil);
    }//GEN-LAST:event_aksiBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorGUI().setVisible(true);
            }
        });
    }
    String tampil;
    double angka1, angka2, hasil;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JComboBox<String> aksiBox;
    private javax.swing.JLabel aksiLabel;
    private javax.swing.JLabel angka1Label;
    private javax.swing.JTextField angka1Text;
    private javax.swing.JTextField angka2Text;
    private javax.swing.JLabel angkaLabel2;
    private javax.swing.JLabel hasilLabel;
    private javax.swing.JTextField hasilText;
    // End of variables declaration//GEN-END:variables
}
